version: "3.8"

services:
    app:
        image: ghcr.io/denikryt/hackbridge-bot:${GIT_COMMIT_HASH:-latest}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            - MONGO_URI=${MONGO_URI}
            - MONGO_DB=${MONGO_DB}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - AVATAR_COLLECTION_NAME=${AVATAR_COLLECTION_NAME:-user_avatars_base}
            - LOG_FILE=${LOG_FILE:-logs/hackbridge_bot.log}
        deploy:
            update_config:
                order: stop-first
        networks:
            - infra_mongo-rs-net

networks:
    infra_mongo-rs-net:
        external: true
